version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: anissadb
      POSTGRES_USER: anissa
      POSTGRES_PASSWORD: anissa
    ports:
      - "5433:5432"
    networks:
      - csa-network

  csa-backend:
    image: anissaras/csa-backend:latest
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/anissadb
      SPRING_DATASOURCE_USERNAME: anissa
      SPRING_DATASOURCE_PASSWORD: anissa
    ports:
      - "8081:8081"
    networks:
      - csa-network

  react-app:
    image: anissaras/react-app:latest
    ports:
      - "3000:3000"
    networks:
      - csa-network

networks:
  csa-network: