version: '3'

services:
  postgresdb:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: anissadb
      POSTGRES_USER: anissa
      POSTGRES_PASSWORD: anissa
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

  spring-boot:
    image: eclipse-temurin:17-jdk-alpine
    volumes:
      - /tmp
    build:
      context: .
      args:
        JAR_FILE: build/libs/*.jar
    depends_on:
      - postgresdb
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/anissadb
      SPRING_DATASOURCE_USERNAME: anissa
      SPRING_DATASOURCE_PASSWORD: anissa

volumes:
  db:
