version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: anissadb
      POSTGRES_USER: anissa
      POSTGRES_PASSWORD: anissa
    ports:
      - "5433:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    networks:
      - csa-network

  csa-backend:
    image: anissaras/csa-backend:latest
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/anissadb
      SPRING_DATASOURCE_USERNAME: anissa
      SPRING_DATASOURCE_PASSWORD: anissa
    ports:
      - "8081:8080"
    networks:
      - csa-network

networks:
  csa-network: