name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installation des dépendances
        run: |
          npm install
          
      - name: Construction de l'image Docker
        run: |
          docker build -t anissaras/csa-back:latest .

      - name: Connexion à Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push vers Docker Hub
        run: |
          docker push anissaras/csa-back:latest
