name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3


      # Build the application with Gradle
      - name: Build with Gradle Wrapper
        run: ./gradlew clean build --no-daemon -x test


      # Login to Docker Hub and push the image (if needed)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t anissaras/java-app .

      - name: Push Docker image to Docker Hub
        run: docker push anissaras/java-app

        # Start Docker Compose with the database service
      - name: Start Docker Compose
        run: docker-compose up -d

      # Run unit tests
      - name: Run tests
        run: ./gradlew test --info

      # Stop Docker Compose after tests
      - name: Stop Docker Compose
        run: docker-compose down