name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Configuration de Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a

      - name: Build app gradle
        uses: ./gradlew build

      - name: Construction Image Docker
        run: docker build -t anissaras/csa-backend:latest .

      - name: Connexion à Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image dockerhub
        run: docker push anissaras/csa-backend:latest

      - name: Docker compose
        run: docker-compose up -d

      - name: test app graddle
        run: ./gradlew test --info

      - name: stop Docker compose
        run: docker-compose down

